.TH signal-rr-recording "1" "October 2015" "Send a signal to processes recorded by rr" "User Commands"
.SH NAME
signal-rr-recording \- send a signal to processes being recorded by rr
.SH SYNOPSIS
.BR signal-rr-recording " <" \fIsignal\fP >
.PP
sends \fIsignal\fP, as understood by \fBkill\fP(1), to all processes
being recorded by \fBrr\fP(1).
.SH SEE ALSO
.PP
.BR rr "(1), " kill "(1), " signal (7)
